# coding: utf-8

"""
    CLOUD API

     IONOS Enterprise-grade Infrastructure as a Service (IaaS) solutions can be managed through the Cloud API, in addition or as an alternative to the \"Data Center Designer\" (DCD) browser-based tool.    Both methods employ consistent concepts and features, deliver similar power and flexibility, and can be used to perform a multitude of management tasks, including adding servers, volumes, configuring networks, and so on.

    The version of the OpenAPI document: 6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ionos_cloud_api_v6_client.images_api import ImagesApi


class TestImagesApi(unittest.TestCase):
    """ImagesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ImagesApi()

    def tearDown(self) -> None:
        pass

    def test_images_delete(self) -> None:
        """Test case for images_delete

        Delete images
        """
        pass

    def test_images_find_by_id(self) -> None:
        """Test case for images_find_by_id

        Retrieve images
        """
        pass

    def test_images_get(self) -> None:
        """Test case for images_get

        List images
        """
        pass

    def test_images_patch(self) -> None:
        """Test case for images_patch

        Partially modify images
        """
        pass

    def test_images_put(self) -> None:
        """Test case for images_put

        Modify an Image by ID
        """
        pass


if __name__ == '__main__':
    unittest.main()
