# coding: utf-8

"""
    CLOUD API

     IONOS Enterprise-grade Infrastructure as a Service (IaaS) solutions can be managed through the Cloud API, in addition or as an alternative to the \"Data Center Designer\" (DCD) browser-based tool.    Both methods employ consistent concepts and features, deliver similar power and flexibility, and can be used to perform a multitude of management tasks, including adding servers, volumes, configuring networks, and so on.

    The version of the OpenAPI document: 6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ionos_cloud_api_v6_client.models.request_metadata import RequestMetadata

class TestRequestMetadata(unittest.TestCase):
    """RequestMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestMetadata:
        """Test RequestMetadata
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestMetadata`
        """
        model = RequestMetadata()
        if include_optional:
            return RequestMetadata(
                created_date = '2015-12-04T14:34:09.809Z',
                created_by = 'user@example.com',
                etag = '45480eb3fbfc31f1d916c1eaa4abdcc3',
                request_status = ionos_cloud_api_v6_client.models.request_status.RequestStatus(
                    id = '15f67991-0f51-4efc-a8ad-ef1fb31a480c', 
                    type = 'request-status', 
                    href = '<RESOURCE-URI>', 
                    metadata = ionos_cloud_api_v6_client.models.request_status_metadata.RequestStatusMetadata(
                        status = 'QUEUED', 
                        message = '', 
                        etag = '45480eb3fbfc31f1d916c1eaa4abdcc3', 
                        targets = [
                            ionos_cloud_api_v6_client.models.request_target.RequestTarget(
                                target = ionos_cloud_api_v6_client.models.resource_reference.ResourceReference(
                                    id = '', 
                                    type = 'resource', 
                                    href = '<RESOURCE-URI>', ), 
                                status = 'QUEUED', )
                            ], ), )
            )
        else:
            return RequestMetadata(
        )
        """

    def testRequestMetadata(self):
        """Test RequestMetadata"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
