# coding: utf-8

"""
    CLOUD API

     IONOS Enterprise-grade Infrastructure as a Service (IaaS) solutions can be managed through the Cloud API, in addition or as an alternative to the \"Data Center Designer\" (DCD) browser-based tool.    Both methods employ consistent concepts and features, deliver similar power and flexibility, and can be used to perform a multitude of management tasks, including adding servers, volumes, configuring networks, and so on.

    The version of the OpenAPI document: 6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ionos_cloud_api_v6_client.ip_blocks_api import IPBlocksApi


class TestIPBlocksApi(unittest.TestCase):
    """IPBlocksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = IPBlocksApi()

    def tearDown(self) -> None:
        pass

    def test_ipblocks_delete(self) -> None:
        """Test case for ipblocks_delete

        Delete IP blocks
        """
        pass

    def test_ipblocks_find_by_id(self) -> None:
        """Test case for ipblocks_find_by_id

        Retrieve IP blocks
        """
        pass

    def test_ipblocks_get(self) -> None:
        """Test case for ipblocks_get

        List IP blocks 
        """
        pass

    def test_ipblocks_patch(self) -> None:
        """Test case for ipblocks_patch

        Partially modify IP blocks
        """
        pass

    def test_ipblocks_post(self) -> None:
        """Test case for ipblocks_post

        Reserve a IP Block
        """
        pass

    def test_ipblocks_put(self) -> None:
        """Test case for ipblocks_put

        Modify a IP Block by ID
        """
        pass


if __name__ == '__main__':
    unittest.main()
