# coding: utf-8

"""
    CLOUD API

     IONOS Enterprise-grade Infrastructure as a Service (IaaS) solutions can be managed through the Cloud API, in addition or as an alternative to the \"Data Center Designer\" (DCD) browser-based tool.    Both methods employ consistent concepts and features, deliver similar power and flexibility, and can be used to perform a multitude of management tasks, including adding servers, volumes, configuring networks, and so on.

    The version of the OpenAPI document: 6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ionos_cloud_api_v6_client.models.nat_gateway_rule_type import NatGatewayRuleType

class TestNatGatewayRuleType(unittest.TestCase):
    """NatGatewayRuleType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNatGatewayRuleType(self):
        """Test NatGatewayRuleType"""
        # inst = NatGatewayRuleType()

if __name__ == '__main__':
    unittest.main()
