# coding: utf-8

"""
    CLOUD API

     IONOS Enterprise-grade Infrastructure as a Service (IaaS) solutions can be managed through the Cloud API, in addition or as an alternative to the \"Data Center Designer\" (DCD) browser-based tool.    Both methods employ consistent concepts and features, deliver similar power and flexibility, and can be used to perform a multitude of management tasks, including adding servers, volumes, configuring networks, and so on.

    The version of the OpenAPI document: 6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ionos_cloud_api_v6_client.flow_logs_api import FlowLogsApi


class TestFlowLogsApi(unittest.TestCase):
    """FlowLogsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FlowLogsApi()

    def tearDown(self) -> None:
        pass

    def test_datacenters_servers_nics_flowlogs_delete(self) -> None:
        """Test case for datacenters_servers_nics_flowlogs_delete

        Delete Flow Logs
        """
        pass

    def test_datacenters_servers_nics_flowlogs_find_by_id(self) -> None:
        """Test case for datacenters_servers_nics_flowlogs_find_by_id

        Retrieve Flow Logs
        """
        pass

    def test_datacenters_servers_nics_flowlogs_get(self) -> None:
        """Test case for datacenters_servers_nics_flowlogs_get

        List Flow Logs
        """
        pass

    def test_datacenters_servers_nics_flowlogs_patch(self) -> None:
        """Test case for datacenters_servers_nics_flowlogs_patch

        Partially modify Flow Logs
        """
        pass

    def test_datacenters_servers_nics_flowlogs_post(self) -> None:
        """Test case for datacenters_servers_nics_flowlogs_post

        Create a Flow Log
        """
        pass

    def test_datacenters_servers_nics_flowlogs_put(self) -> None:
        """Test case for datacenters_servers_nics_flowlogs_put

        Modify Flow Logs
        """
        pass


if __name__ == '__main__':
    unittest.main()
