# coding: utf-8

"""
    CLOUD API

     IONOS Enterprise-grade Infrastructure as a Service (IaaS) solutions can be managed through the Cloud API, in addition or as an alternative to the \"Data Center Designer\" (DCD) browser-based tool.    Both methods employ consistent concepts and features, deliver similar power and flexibility, and can be used to perform a multitude of management tasks, including adding servers, volumes, configuring networks, and so on.

    The version of the OpenAPI document: 6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ionos_cloud_api_v6_client.models.kubernetes_node_pool_properties_for_post import KubernetesNodePoolPropertiesForPost

class TestKubernetesNodePoolPropertiesForPost(unittest.TestCase):
    """KubernetesNodePoolPropertiesForPost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> KubernetesNodePoolPropertiesForPost:
        """Test KubernetesNodePoolPropertiesForPost
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `KubernetesNodePoolPropertiesForPost`
        """
        model = KubernetesNodePoolPropertiesForPost()
        if include_optional:
            return KubernetesNodePoolPropertiesForPost(
                name = 'K8s-node-pool',
                datacenter_id = '1e072e52-2ed3-492f-b6b6-c6b116907521',
                node_count = 2,
                server_type = 'DedicatedCore',
                cpu_family = 'INTEL_ICELAKE',
                cores_count = 4,
                ram_size = 2048,
                availability_zone = 'AUTO',
                storage_type = 'HDD',
                storage_size = 100,
                k8s_version = '1.15.4',
                maintenance_window = ionos_cloud_api_v6_client.models.kubernetes_maintenance_window.KubernetesMaintenanceWindow(
                    day_of_the_week = 'Monday', 
                    time = '13:00:00', ),
                auto_scaling = ionos_cloud_api_v6_client.models.kubernetes_auto_scaling.KubernetesAutoScaling(
                    min_node_count = 1, 
                    max_node_count = 3, ),
                lans = [
                    ionos_cloud_api_v6_client.models.kubernetes_node_pool_lan.KubernetesNodePoolLan(
                        datacenter_id = '00000000-0000-0000-0000-000000000000', 
                        id = 3, 
                        dhcp = True, 
                        routes = [
                            ionos_cloud_api_v6_client.models.kubernetes_node_pool_lan_routes.KubernetesNodePoolLanRoutes(
                                network = '1.2.3.4/24', 
                                gateway_ip = '10.1.5.16', )
                            ], )
                    ],
                labels = {
                    'key' : ''
                    },
                annotations = {
                    'key' : ''
                    },
                public_ips = ["81.173.1.2","82.231.2.5","92.221.2.4"]
            )
        else:
            return KubernetesNodePoolPropertiesForPost(
                name = 'K8s-node-pool',
                datacenter_id = '1e072e52-2ed3-492f-b6b6-c6b116907521',
                node_count = 2,
                cores_count = 4,
                ram_size = 2048,
                availability_zone = 'AUTO',
                storage_type = 'HDD',
                storage_size = 100,
        )
        """

    def testKubernetesNodePoolPropertiesForPost(self):
        """Test KubernetesNodePoolPropertiesForPost"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
