# coding: utf-8

"""
    CLOUD API

     IONOS Enterprise-grade Infrastructure as a Service (IaaS) solutions can be managed through the Cloud API, in addition or as an alternative to the \"Data Center Designer\" (DCD) browser-based tool.    Both methods employ consistent concepts and features, deliver similar power and flexibility, and can be used to perform a multitude of management tasks, including adding servers, volumes, configuring networks, and so on.

    The version of the OpenAPI document: 6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ionos_cloud_api_v6_client.data_centers_api import DataCentersApi


class TestDataCentersApi(unittest.TestCase):
    """DataCentersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DataCentersApi()

    def tearDown(self) -> None:
        pass

    def test_datacenters_delete(self) -> None:
        """Test case for datacenters_delete

        Delete data centers
        """
        pass

    def test_datacenters_find_by_id(self) -> None:
        """Test case for datacenters_find_by_id

        Retrieve data centers
        """
        pass

    def test_datacenters_get(self) -> None:
        """Test case for datacenters_get

        List your data centers
        """
        pass

    def test_datacenters_patch(self) -> None:
        """Test case for datacenters_patch

        Partially modify a Data Center by ID
        """
        pass

    def test_datacenters_post(self) -> None:
        """Test case for datacenters_post

        Create a Data Center
        """
        pass

    def test_datacenters_put(self) -> None:
        """Test case for datacenters_put

        Modify a Data Center by ID
        """
        pass


if __name__ == '__main__':
    unittest.main()
