# coding: utf-8

"""
    CLOUD API

     IONOS Enterprise-grade Infrastructure as a Service (IaaS) solutions can be managed through the Cloud API, in addition or as an alternative to the \"Data Center Designer\" (DCD) browser-based tool.    Both methods employ consistent concepts and features, deliver similar power and flexibility, and can be used to perform a multitude of management tasks, including adding servers, volumes, configuring networks, and so on.

    The version of the OpenAPI document: 6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ionos_cloud_api_v6_client.target_groups_api import TargetGroupsApi


class TestTargetGroupsApi(unittest.TestCase):
    """TargetGroupsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TargetGroupsApi()

    def tearDown(self) -> None:
        pass

    def test_target_groups_delete(self) -> None:
        """Test case for target_groups_delete

        Delete a Target Group by ID
        """
        pass

    def test_targetgroups_find_by_target_group_id(self) -> None:
        """Test case for targetgroups_find_by_target_group_id

        Get a Target Group by ID
        """
        pass

    def test_targetgroups_get(self) -> None:
        """Test case for targetgroups_get

        Get Target Groups
        """
        pass

    def test_targetgroups_patch(self) -> None:
        """Test case for targetgroups_patch

        Partially Modify a Target Group by ID
        """
        pass

    def test_targetgroups_post(self) -> None:
        """Test case for targetgroups_post

        Create a Target Group
        """
        pass

    def test_targetgroups_put(self) -> None:
        """Test case for targetgroups_put

        Modify a Target Group by ID
        """
        pass


if __name__ == '__main__':
    unittest.main()
