# coding: utf-8

"""
    CLOUD API

     IONOS Enterprise-grade Infrastructure as a Service (IaaS) solutions can be managed through the Cloud API, in addition or as an alternative to the \"Data Center Designer\" (DCD) browser-based tool.    Both methods employ consistent concepts and features, deliver similar power and flexibility, and can be used to perform a multitude of management tasks, including adding servers, volumes, configuring networks, and so on.

    The version of the OpenAPI document: 6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ionos_cloud_api_v6_client.kubernetes_api import KubernetesApi


class TestKubernetesApi(unittest.TestCase):
    """KubernetesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = KubernetesApi()

    def tearDown(self) -> None:
        pass

    def test_k8s_delete(self) -> None:
        """Test case for k8s_delete

        Delete a Kubernetes Cluster by ID
        """
        pass

    def test_k8s_find_by_cluster_id(self) -> None:
        """Test case for k8s_find_by_cluster_id

        Get a Kubernetes Cluster by ID
        """
        pass

    def test_k8s_get(self) -> None:
        """Test case for k8s_get

        Get Kubernetes Clusters
        """
        pass

    def test_k8s_kubeconfig_get(self) -> None:
        """Test case for k8s_kubeconfig_get

        Get Kubernetes Configuration File
        """
        pass

    def test_k8s_nodepools_delete(self) -> None:
        """Test case for k8s_nodepools_delete

        Delete a Kubernetes Node Pool by ID
        """
        pass

    def test_k8s_nodepools_find_by_id(self) -> None:
        """Test case for k8s_nodepools_find_by_id

        Get a Kubernetes Node Pool by ID
        """
        pass

    def test_k8s_nodepools_get(self) -> None:
        """Test case for k8s_nodepools_get

        Get Kubernetes Node Pools
        """
        pass

    def test_k8s_nodepools_nodes_delete(self) -> None:
        """Test case for k8s_nodepools_nodes_delete

        Delete a Kubernetes Node by ID
        """
        pass

    def test_k8s_nodepools_nodes_find_by_id(self) -> None:
        """Test case for k8s_nodepools_nodes_find_by_id

        Get Kubernetes Node by ID
        """
        pass

    def test_k8s_nodepools_nodes_get(self) -> None:
        """Test case for k8s_nodepools_nodes_get

        Get Kubernetes Nodes
        """
        pass

    def test_k8s_nodepools_nodes_replace_post(self) -> None:
        """Test case for k8s_nodepools_nodes_replace_post

        Recreate a Kubernetes Node by ID
        """
        pass

    def test_k8s_nodepools_post(self) -> None:
        """Test case for k8s_nodepools_post

        Create a Kubernetes Node Pool
        """
        pass

    def test_k8s_nodepools_put(self) -> None:
        """Test case for k8s_nodepools_put

        Modify a Kubernetes Node Pool by ID
        """
        pass

    def test_k8s_post(self) -> None:
        """Test case for k8s_post

        Create a Kubernetes Cluster
        """
        pass

    def test_k8s_put(self) -> None:
        """Test case for k8s_put

        Modify a Kubernetes Cluster by ID
        """
        pass

    def test_k8s_versions_default_get(self) -> None:
        """Test case for k8s_versions_default_get

        Get Default Kubernetes Version
        """
        pass

    def test_k8s_versions_get(self) -> None:
        """Test case for k8s_versions_get

        Get Kubernetes Versions
        """
        pass


if __name__ == '__main__':
    unittest.main()
