# coding: utf-8

"""
    CLOUD API

     IONOS Enterprise-grade Infrastructure as a Service (IaaS) solutions can be managed through the Cloud API, in addition or as an alternative to the \"Data Center Designer\" (DCD) browser-based tool.    Both methods employ consistent concepts and features, deliver similar power and flexibility, and can be used to perform a multitude of management tasks, including adding servers, volumes, configuring networks, and so on.

    The version of the OpenAPI document: 6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ionos_cloud_api_v6_client.user_s3_keys_api import UserS3KeysApi


class TestUserS3KeysApi(unittest.TestCase):
    """UserS3KeysApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UserS3KeysApi()

    def tearDown(self) -> None:
        pass

    def test_um_users_s3keys_delete(self) -> None:
        """Test case for um_users_s3keys_delete

        Delete Object storage keys
        """
        pass

    def test_um_users_s3keys_find_by_key_id(self) -> None:
        """Test case for um_users_s3keys_find_by_key_id

        Retrieve user Object storage keys by key ID
        """
        pass

    def test_um_users_s3keys_get(self) -> None:
        """Test case for um_users_s3keys_get

        List user Object storage keys
        """
        pass

    def test_um_users_s3keys_post(self) -> None:
        """Test case for um_users_s3keys_post

        Create user Object storage keys
        """
        pass

    def test_um_users_s3keys_put(self) -> None:
        """Test case for um_users_s3keys_put

        Modify a Object storage Key by Key ID
        """
        pass

    def test_um_users_s3ssourl_get(self) -> None:
        """Test case for um_users_s3ssourl_get

        Retrieve Object storage single sign-on URLs
        """
        pass


if __name__ == '__main__':
    unittest.main()
