# coding: utf-8

"""
    CLOUD API

     IONOS Enterprise-grade Infrastructure as a Service (IaaS) solutions can be managed through the Cloud API, in addition or as an alternative to the \"Data Center Designer\" (DCD) browser-based tool.    Both methods employ consistent concepts and features, deliver similar power and flexibility, and can be used to perform a multitude of management tasks, including adding servers, volumes, configuring networks, and so on.

    The version of the OpenAPI document: 6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ionos_cloud_api_v6_client.models.list_of_ids import ListOfIds

class TestListOfIds(unittest.TestCase):
    """ListOfIds unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListOfIds:
        """Test ListOfIds
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListOfIds`
        """
        model = ListOfIds()
        if include_optional:
            return ListOfIds(
                ids = ["ac51b8e4-050c-4941-b7cd-43923422fe6e","ea737d87-8754-4a42-b97c-0b1a8f619de5"]
            )
        else:
            return ListOfIds(
                ids = ["ac51b8e4-050c-4941-b7cd-43923422fe6e","ea737d87-8754-4a42-b97c-0b1a8f619de5"],
        )
        """

    def testListOfIds(self):
        """Test ListOfIds"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
