# coding: utf-8

"""
    CLOUD API

     IONOS Enterprise-grade Infrastructure as a Service (IaaS) solutions can be managed through the Cloud API, in addition or as an alternative to the \"Data Center Designer\" (DCD) browser-based tool.    Both methods employ consistent concepts and features, deliver similar power and flexibility, and can be used to perform a multitude of management tasks, including adding servers, volumes, configuring networks, and so on.

    The version of the OpenAPI document: 6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ionos_cloud_api_v6_client.network_load_balancers_api import NetworkLoadBalancersApi


class TestNetworkLoadBalancersApi(unittest.TestCase):
    """NetworkLoadBalancersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = NetworkLoadBalancersApi()

    def tearDown(self) -> None:
        pass

    def test_datacenters_networkloadbalancers_delete(self) -> None:
        """Test case for datacenters_networkloadbalancers_delete

        Delete Network Load Balancers
        """
        pass

    def test_datacenters_networkloadbalancers_find_by_network_load_balancer_id(self) -> None:
        """Test case for datacenters_networkloadbalancers_find_by_network_load_balancer_id

        Retrieve Network Load Balancers
        """
        pass

    def test_datacenters_networkloadbalancers_flowlogs_delete(self) -> None:
        """Test case for datacenters_networkloadbalancers_flowlogs_delete

        Delete NLB Flow Logs
        """
        pass

    def test_datacenters_networkloadbalancers_flowlogs_find_by_flow_log_id(self) -> None:
        """Test case for datacenters_networkloadbalancers_flowlogs_find_by_flow_log_id

        Retrieve NLB Flow Logs
        """
        pass

    def test_datacenters_networkloadbalancers_flowlogs_get(self) -> None:
        """Test case for datacenters_networkloadbalancers_flowlogs_get

        List NLB Flow Logs
        """
        pass

    def test_datacenters_networkloadbalancers_flowlogs_patch(self) -> None:
        """Test case for datacenters_networkloadbalancers_flowlogs_patch

        Partially modify NLB Flow Logs
        """
        pass

    def test_datacenters_networkloadbalancers_flowlogs_post(self) -> None:
        """Test case for datacenters_networkloadbalancers_flowlogs_post

        Create a NLB Flow Log
        """
        pass

    def test_datacenters_networkloadbalancers_flowlogs_put(self) -> None:
        """Test case for datacenters_networkloadbalancers_flowlogs_put

        Modify NLB Flow Logs
        """
        pass

    def test_datacenters_networkloadbalancers_forwardingrules_delete(self) -> None:
        """Test case for datacenters_networkloadbalancers_forwardingrules_delete

        Delete NLB forwarding rules
        """
        pass

    def test_datacenters_networkloadbalancers_forwardingrules_find_by_forwarding_rule_id(self) -> None:
        """Test case for datacenters_networkloadbalancers_forwardingrules_find_by_forwarding_rule_id

        Retrieve NLB forwarding rules
        """
        pass

    def test_datacenters_networkloadbalancers_forwardingrules_get(self) -> None:
        """Test case for datacenters_networkloadbalancers_forwardingrules_get

        List NLB forwarding rules
        """
        pass

    def test_datacenters_networkloadbalancers_forwardingrules_patch(self) -> None:
        """Test case for datacenters_networkloadbalancers_forwardingrules_patch

        Partially modify NLB forwarding rules
        """
        pass

    def test_datacenters_networkloadbalancers_forwardingrules_post(self) -> None:
        """Test case for datacenters_networkloadbalancers_forwardingrules_post

        Create a NLB Forwarding Rule
        """
        pass

    def test_datacenters_networkloadbalancers_forwardingrules_put(self) -> None:
        """Test case for datacenters_networkloadbalancers_forwardingrules_put

        Modify NLB forwarding rules
        """
        pass

    def test_datacenters_networkloadbalancers_get(self) -> None:
        """Test case for datacenters_networkloadbalancers_get

        List Network Load Balancers
        """
        pass

    def test_datacenters_networkloadbalancers_patch(self) -> None:
        """Test case for datacenters_networkloadbalancers_patch

        Partially modify Network Load Balancers
        """
        pass

    def test_datacenters_networkloadbalancers_post(self) -> None:
        """Test case for datacenters_networkloadbalancers_post

        Create a Network Load Balancer
        """
        pass

    def test_datacenters_networkloadbalancers_put(self) -> None:
        """Test case for datacenters_networkloadbalancers_put

        Modify Network Load Balancers
        """
        pass


if __name__ == '__main__':
    unittest.main()
