# coding: utf-8

"""
    CLOUD API

     IONOS Enterprise-grade Infrastructure as a Service (IaaS) solutions can be managed through the Cloud API, in addition or as an alternative to the \"Data Center Designer\" (DCD) browser-based tool.    Both methods employ consistent concepts and features, deliver similar power and flexibility, and can be used to perform a multitude of management tasks, including adding servers, volumes, configuring networks, and so on.

    The version of the OpenAPI document: 6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ionos_cloud_api_v6_client.models.kubernetes_nodes import KubernetesNodes

class TestKubernetesNodes(unittest.TestCase):
    """KubernetesNodes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> KubernetesNodes:
        """Test KubernetesNodes
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `KubernetesNodes`
        """
        model = KubernetesNodes()
        if include_optional:
            return KubernetesNodes(
                id = '1e072e52-2ed3-492f-b6b6-c6b116907527/nodepools',
                type = 'collection',
                href = 'https://api.ionos.com/cloudapi/v6/k8s/30f8a4f6-6515-4c34-b49d-dea807453b90/nodepools/bfdf67bd-5665-4245-8096-7c7991f02f3f/nodes',
                items = [
                    ionos_cloud_api_v6_client.models.kubernetes_node.KubernetesNode(
                        id = '1e072e52-2ed3-492f-b6b6-c6b116907527', 
                        type = 'node', 
                        href = 'https://api.ionos.com/cloudapi/v6/k8s/30f8a4f6-6515-4c34-b49d-dea807453b90/nodepools/bfdf67bd-5665-4245-8096-7c7991f02f3f/nodes/81892fdb-d97e-4919-baf9-2b3a923f5401', 
                        metadata = ionos_cloud_api_v6_client.models.kubernetes_node_metadata.KubernetesNodeMetadata(
                            etag = '45480eb3fbfc31f1d916c1eaa4abdcc3', 
                            created_date = '2015-12-04T14:34:09.809Z', 
                            last_modified_date = '2015-12-04T14:34:09.809Z', 
                            state = 'READY', 
                            last_software_updated_date = '2015-12-04T14:34:09.809Z', ), 
                        properties = ionos_cloud_api_v6_client.models.kubernetes_node_properties.KubernetesNodeProperties(
                            name = 'K8s-node', 
                            public_ip = '192.168.23.2', 
                            private_ip = '192.168.23.2', 
                            k8s_version = '1.15.4', ), )
                    ]
            )
        else:
            return KubernetesNodes(
        )
        """

    def testKubernetesNodes(self):
        """Test KubernetesNodes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
