# coding: utf-8

"""
    CLOUD API

     IONOS Enterprise-grade Infrastructure as a Service (IaaS) solutions can be managed through the Cloud API, in addition or as an alternative to the \"Data Center Designer\" (DCD) browser-based tool.    Both methods employ consistent concepts and features, deliver similar power and flexibility, and can be used to perform a multitude of management tasks, including adding servers, volumes, configuring networks, and so on.

    The version of the OpenAPI document: 6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ionos_cloud_api_v6_client.models.s3_keys import S3Keys

class TestS3Keys(unittest.TestCase):
    """S3Keys unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> S3Keys:
        """Test S3Keys
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `S3Keys`
        """
        model = S3Keys()
        if include_optional:
            return S3Keys(
                id = '15f67991-0f51-4efc-a8ad-ef1fb31a480c',
                type = 'datacenter',
                href = 'https://<API_HOST>/cloudapi/v6/um/users/9b1b4c62-1466-11e7-87d3-d7bb7dac0087/s3keys',
                items = [
                    ionos_cloud_api_v6_client.models.s3_key.S3Key(
                        id = '15f67991-0f51-4efc-a8ad-ef1fb31a480c', 
                        type = 'group', 
                        href = 'https://<API_HOST>/cloudapi/v6/um/users/15f67991-0f51-4efc-a8ad-ef1fb31a480c/s3keys/78fa888e106456c1482d', 
                        metadata = ionos_cloud_api_v6_client.models.s3_key_metadata.S3KeyMetadata(
                            etag = '45480eb3fbfc31f1d916c1eaa4abdcc3', 
                            created_date = '2015-12-04T14:34:09.809Z', 
                            created_by = 'ionos:identity:::users/63cef532-26fe-4a64-a4e0-de7c8a506c90', 
                            created_by_user_id = '63cef532-26fe-4a64-a4e0-de7c8a506c90', 
                            last_modified_date = '2015-12-04T14:34:09.809Z', 
                            last_modified_by = 'ionos:identity:::users/63cef532-26fe-4a64-a4e0-de7c8a506c90', 
                            last_modified_by_user_id = '63cef532-26fe-4a64-a4e0-de7c8a506c90', ), 
                        properties = ionos_cloud_api_v6_client.models.s3_key_properties.S3KeyProperties(
                            secret_key = 'tFVkUARsoeCdntQs2jVSyGG6TMPfPZ+ghnsWj/gG', 
                            active = True, ), )
                    ]
            )
        else:
            return S3Keys(
        )
        """

    def testS3Keys(self):
        """Test S3Keys"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
