# coding: utf-8

"""
    CLOUD API

     IONOS Enterprise-grade Infrastructure as a Service (IaaS) solutions can be managed through the Cloud API, in addition or as an alternative to the \"Data Center Designer\" (DCD) browser-based tool.    Both methods employ consistent concepts and features, deliver similar power and flexibility, and can be used to perform a multitude of management tasks, including adding servers, volumes, configuring networks, and so on.

    The version of the OpenAPI document: 6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class NatGatewayRuleType(str, Enum):
    """
    NatGatewayRuleType
    """

    """
    allowed enum values
    """
    SNAT = 'SNAT'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of NatGatewayRuleType from a JSON string"""
        return cls(json.loads(json_str))


