# coding: utf-8

"""
    CLOUD API

     IONOS Enterprise-grade Infrastructure as a Service (IaaS) solutions can be managed through the Cloud API, in addition or as an alternative to the \"Data Center Designer\" (DCD) browser-based tool.    Both methods employ consistent concepts and features, deliver similar power and flexibility, and can be used to perform a multitude of management tasks, including adding servers, volumes, configuring networks, and so on.

    The version of the OpenAPI document: 6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class SnapshotProperties(BaseModel):
    """
    SnapshotProperties
    """ # noqa: E501
    name: Optional[StrictStr] = Field(default=None, description="The name of the  resource.")
    description: Optional[StrictStr] = Field(default=None, description="Human-readable description.")
    location: Optional[StrictStr] = Field(default=None, description="Location of that image/snapshot. ")
    size: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The size of the image in GB.")
    sec_auth_protection: Optional[StrictBool] = Field(default=None, description="Boolean value representing if the snapshot requires extra protection, such as two-step verification.", alias="secAuthProtection")
    cpu_hot_plug: Optional[StrictBool] = Field(default=None, description="Hot-plug capable CPU (no reboot required).", alias="cpuHotPlug")
    cpu_hot_unplug: Optional[StrictBool] = Field(default=None, description="Hot-unplug capable CPU (no reboot required).", alias="cpuHotUnplug")
    ram_hot_plug: Optional[StrictBool] = Field(default=None, description="Hot-plug capable RAM (no reboot required).", alias="ramHotPlug")
    ram_hot_unplug: Optional[StrictBool] = Field(default=None, description="Hot-unplug capable RAM (no reboot required).", alias="ramHotUnplug")
    nic_hot_plug: Optional[StrictBool] = Field(default=None, description="Hot-plug capable NIC (no reboot required).", alias="nicHotPlug")
    nic_hot_unplug: Optional[StrictBool] = Field(default=None, description="Hot-unplug capable NIC (no reboot required).", alias="nicHotUnplug")
    disc_virtio_hot_plug: Optional[StrictBool] = Field(default=None, description="Hot-plug capable Virt-IO drive (no reboot required).", alias="discVirtioHotPlug")
    disc_virtio_hot_unplug: Optional[StrictBool] = Field(default=None, description="Hot-unplug capable Virt-IO drive (no reboot required). Not supported with Windows VMs.", alias="discVirtioHotUnplug")
    disc_scsi_hot_plug: Optional[StrictBool] = Field(default=None, description="Hot-plug capable SCSI drive (no reboot required).", alias="discScsiHotPlug")
    expose_serial: Optional[StrictBool] = Field(default=False, description="If set to `true` will expose the serial id of the disk attached to the server. If set to `false` will not expose the serial id. Some operating systems or software solutions require the serial id to be exposed to work properly. Exposing the serial  can influence licensed software (e.g. Windows) behavior", alias="exposeSerial")
    require_legacy_bios: Optional[StrictBool] = Field(default=True, description="Indicates if the image requires the legacy BIOS for compatibility or specific needs.", alias="requireLegacyBios")
    disc_scsi_hot_unplug: Optional[StrictBool] = Field(default=None, description="Is capable of SCSI drive hot unplug (no reboot required). This works only for non-Windows virtual Machines.", alias="discScsiHotUnplug")
    licence_type: Optional[StrictStr] = Field(default=None, description="OS type of this snapshot", alias="licenceType")
    application_type: Optional[StrictStr] = Field(default='UNKNOWN', description="The type of application that is hosted on this resource.  Only public images can have an Application type different than UNKNOWN.", alias="applicationType")
    __properties: ClassVar[List[str]] = ["name", "description", "location", "size", "secAuthProtection", "cpuHotPlug", "cpuHotUnplug", "ramHotPlug", "ramHotUnplug", "nicHotPlug", "nicHotUnplug", "discVirtioHotPlug", "discVirtioHotUnplug", "discScsiHotPlug", "exposeSerial", "requireLegacyBios", "discScsiHotUnplug", "licenceType", "applicationType"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SnapshotProperties from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "location",
            "size",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SnapshotProperties from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "description": obj.get("description"),
            "location": obj.get("location"),
            "size": obj.get("size"),
            "secAuthProtection": obj.get("secAuthProtection"),
            "cpuHotPlug": obj.get("cpuHotPlug"),
            "cpuHotUnplug": obj.get("cpuHotUnplug"),
            "ramHotPlug": obj.get("ramHotPlug"),
            "ramHotUnplug": obj.get("ramHotUnplug"),
            "nicHotPlug": obj.get("nicHotPlug"),
            "nicHotUnplug": obj.get("nicHotUnplug"),
            "discVirtioHotPlug": obj.get("discVirtioHotPlug"),
            "discVirtioHotUnplug": obj.get("discVirtioHotUnplug"),
            "discScsiHotPlug": obj.get("discScsiHotPlug"),
            "exposeSerial": obj.get("exposeSerial") if obj.get("exposeSerial") is not None else False,
            "requireLegacyBios": obj.get("requireLegacyBios") if obj.get("requireLegacyBios") is not None else True,
            "discScsiHotUnplug": obj.get("discScsiHotUnplug"),
            "licenceType": obj.get("licenceType"),
            "applicationType": obj.get("applicationType") if obj.get("applicationType") is not None else 'UNKNOWN'
        })
        return _obj


